name: cv
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - argcomplete=1.12.3
  - argon2-cffi=20.1.0
  - async_generator=1.10
  - attrs=21.2.0
  - backcall=0.2.0
  - blas=1.0
  - bleach=4.0.0
  - bottleneck=1.3.2
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - ca-certificates=2020.10.14
  - certifi=2020.6.20
  - cffi=1.14.5
  - click=8.0.3
  - cycler=0.11.0
  - dbus=1.13.18
  - debugpy=1.4.1
  - decorator=5.1.0
  - defusedxml=0.7.1
  - dlib=19.22.0
  - entrypoints=0.3
  - expat=2.4.1
  - face_recognition=1.3.0
  - face_recognition_models=0.3.0
  - fontconfig=2.13.1
  - fonttools=4.25.0
  - freetype=2.11.0
  - glib=2.69.1
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - icu=58.2
  - importlib-metadata=4.8.1
  - importlib_metadata=4.8.1
  - intel-openmp=2021.4.0
  - ipykernel=6.4.1
  - ipython=7.29.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.5
  - jedi=0.18.0
  - jinja2=3.0.2
  - joblib=0.17.0
  - jpeg=9d
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=7.0.1
  - jupyter_console=6.4.0
  - jupyter_core=4.9.1
  - jupyterlab_pygments=0.1.2
  - jupyterlab_widgets=1.0.0
  - kiwisolver=1.3.1
  - ld_impl_linux-64=2.35.1
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgfortran-ng=7.3.0
  - libgomp=9.3.0
  - liblapack=3.9.0
  - libpng=1.6.37
  - libsodium=1.0.18
  - libstdcxx-ng=9.3.0
  - libtiff=4.0.10
  - libuuid=1.0.3
  - libxcb=1.14
  - libxml2=2.9.12
  - lz4-c=1.9.3
  - markupsafe=2.0.1
  - matplotlib=3.4.3
  - matplotlib-base=3.4.3
  - matplotlib-inline=0.1.2
  - mistune=0.8.4
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - munkres=1.1.4
  - nbclient=0.5.3
  - nbconvert=6.1.0
  - nbformat=5.1.3
  - ncurses=6.3
  - nest-asyncio=1.5.1
  - notebook=6.4.5
  - numexpr=2.7.3
  - numpy-base=1.21.2
  - olefile=0.46
  - openssl=1.1.1l
  - packaging=21.0
  - pandas=1.3.4
  - pandocfilters=1.4.3
  - parso=0.8.2
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=21.0.1
  - prometheus_client=0.11.0
  - prompt-toolkit=3.0.20
  - prompt_toolkit=3.0.20
  - ptyprocess=0.7.0
  - pycparser=2.21
  - pygments=2.10.0
  - pyparsing=3.0.4
  - pyqt=5.9.2
  - pyrsistent=0.18.0
  - python=3.7.11
  - python-dateutil=2.8.2
  - python_abi=3.7
  - pytz=2021.3
  - pyzmq=22.2.1
  - qt=5.9.7
  - qtconsole=5.1.1
  - qtpy=1.10.0
  - readline=8.1
  - scikit-learn=0.23.2
  - scipy=1.6.2
  - seaborn=0.11.0
  - send2trash=1.8.0
  - setuptools=58.0.4
  - sip=4.19.8
  - six=1.16.0
  - sqlite=3.36.0
  - terminado=0.9.4
  - testpath=0.5.0
  - threadpoolctl=2.1.0
  - tk=8.6.11
  - tornado=6.1
  - traitlets=5.1.0
  - typing_extensions=3.10.0.2
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.37.0
  - widgetsnbextension=3.5.1
  - xz=5.2.5
  - zeromq=4.3.4
  - zipp=3.6.0
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - absl-py==1.0.0
    - astunparse==1.6.3
    - cached-property==1.5.2
    - cachetools==4.2.4
    - charset-normalizer==2.0.7
    - cvlib==0.2.6
    - flatbuffers==2.0
    - gast==0.4.0
    - google-auth==2.3.3
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - grpcio==1.41.1
    - h5py==3.5.0
    - idna==3.3
    - imageio==2.10.4
    - imutils==0.5.4
    - keras==2.7.0
    - keras-preprocessing==1.1.2
    - libclang==12.0.0
    - markdown==3.3.4
    - numpy==1.21.4
    - oauthlib==3.1.1
    - opencv-python==4.3.0.36
    - opt-einsum==3.3.0
    - pillow==8.4.0
    - progressbar==2.5
    - protobuf==3.19.1
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pyqt6==6.2.1
    - pyqt6-qt6==6.2.1
    - pyqt6-sip==13.1.0
    - requests==2.26.0
    - requests-oauthlib==1.3.0
    - rsa==4.7.2
    - tensorboard==2.7.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.0
    - tensorflow==2.7.0
    - tensorflow-estimator==2.7.0
    - tensorflow-io-gcs-filesystem==0.22.0
    - termcolor==1.1.0
    - urllib3==1.26.7
    - werkzeug==2.0.2
    - wrapt==1.13.3
