# Form implementation generated from reading ui file 'frame.ui'
#
# Created by: PyQt6 UI code generator 6.2.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ContainerHome(object):
    def setupUi(self, ContainerHome):
        ContainerHome.setObjectName("ContainerHome")
        ContainerHome.resize(1051, 752)
        self.main_page = QtWidgets.QFrame(ContainerHome)
        self.main_page.setEnabled(True)
        self.main_page.setGeometry(QtCore.QRect(0, 0, 1051, 751))
        self.main_page.setMouseTracking(False)
        self.main_page.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.main_page.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.main_page.setLineWidth(4)
        self.main_page.setObjectName("main_page")
        self.img_page = QtWidgets.QFrame(self.main_page)
        self.img_page.setEnabled(True)
        self.img_page.setGeometry(QtCore.QRect(0, 0, 1051, 751))
        self.img_page.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.img_page.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.img_page.setLineWidth(4)
        self.img_page.setObjectName("img_page")
        self.windowslabel = QtWidgets.QLabel(self.img_page)
        self.windowslabel.setGeometry(QtCore.QRect(40, 130, 640, 480))
        self.windowslabel.setMinimumSize(QtCore.QSize(640, 480))
        self.windowslabel.setMaximumSize(QtCore.QSize(640, 480))
        self.windowslabel.setText("")
        self.windowslabel.setObjectName("windowslabel")
        self.btn_home_video = QtWidgets.QPushButton(self.img_page)
        self.btn_home_video.setGeometry(QtCore.QRect(770, 350, 230, 61))
        self.btn_home_video.setObjectName("btn_home_video")
        self.btn_home_img = QtWidgets.QPushButton(self.img_page)
        self.btn_home_img.setGeometry(QtCore.QRect(770, 490, 230, 61))
        self.btn_home_img.setObjectName("btn_home_img")
        self.btn_home_cam = QtWidgets.QPushButton(self.img_page)
        self.btn_home_cam.setGeometry(QtCore.QRect(770, 620, 230, 61))
        self.btn_home_cam.setObjectName("btn_home_cam")
        self.title_home = QtWidgets.QLabel(self.img_page)
        self.title_home.setEnabled(True)
        self.title_home.setGeometry(QtCore.QRect(300, 40, 491, 61))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(24)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.title_home.setFont(font)
        self.title_home.setAutoFillBackground(False)
        self.title_home.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.title_home.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.title_home.setObjectName("title_home")
        self.stop_btn = QtWidgets.QPushButton(self.img_page)
        self.stop_btn.setGeometry(QtCore.QRect(320, 660, 161, 41))
        self.stop_btn.setObjectName("stop_btn")

        self.retranslateUi(ContainerHome)
        QtCore.QMetaObject.connectSlotsByName(ContainerHome)

    def retranslateUi(self, ContainerHome):
        _translate = QtCore.QCoreApplication.translate
        ContainerHome.setWindowTitle(_translate("ContainerHome", "Gender Age Detection "))
        self.btn_home_video.setText(_translate("ContainerHome", "Video Face Detection"))
        self.btn_home_img.setText(_translate("ContainerHome", "Image Face Detection"))
        self.btn_home_cam.setText(_translate("ContainerHome", "WebCam Face Detection"))
        self.title_home.setText(_translate("ContainerHome", "Age Gender Detection Software"))
        self.stop_btn.setText(_translate("ContainerHome", "Stop"))
