# Form implementation generated from reading ui file 'framecam.ui'
#
# Created by: PyQt6 UI code generator 6.2.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_webcampage(object):
    def setupUi(self, webcampage):
        webcampage.setObjectName("webcampage")
        webcampage.resize(1051, 749)
        self.windowscam = QtWidgets.QLabel(webcampage)
        self.windowscam.setGeometry(QtCore.QRect(210, 110, 640, 480))
        self.windowscam.setMinimumSize(QtCore.QSize(640, 480))
        self.windowscam.setMaximumSize(QtCore.QSize(640, 480))
        self.windowscam.setText("")
        self.windowscam.setObjectName("windowscam")

        self.retranslateUi(webcampage)
        QtCore.QMetaObject.connectSlotsByName(webcampage)

    def retranslateUi(self, webcampage):
        _translate = QtCore.QCoreApplication.translate
        webcampage.setWindowTitle(_translate("webcampage", "webcam"))
